name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: dmg
          - os: windows-latest  
            target: nsis
          # Commenting out Linux until we fix the issues
          # - os: ubuntu-latest
          #   target: AppImage
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build app for ${{ matrix.target }}
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload ${{ matrix.os }} artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ${{ matrix.os }}-${{ matrix.target }}
          path: |
            dist/*.exe
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
          retention-days: 7
          if-no-files-found: ignore
          
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          
      - name: List downloaded artifacts
        run: |
          echo "Downloaded artifacts:"
          find ./artifacts -type f -name "*" || echo "No artifacts found"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.exe
            artifacts/**/*.dmg
          generate_release_notes: true
          body: |
            ## 🍅 Pomodoro Timer v${{ github.ref_name }}
            
            A minimal, beautiful Pomodoro timer desktop app.
            
            ### ✨ Features
            - 25/5/25/5/25/5/25/15 Pomodoro cycles
            - Clean, minimal dark theme interface
            - System tray integration with 🍅 icon
            - Keyboard shortcuts (Space to start/pause)
            - Desktop notifications
            - Add your own lofi music files
            
            ### 📥 Downloads
            - **Windows**: Download the `.exe` installer
            - **macOS**: Download the `.dmg` disk image
            - **Linux**: Coming soon! 🐧
            
            ### 🎵 Setup Your Music
            1. Install the app
            2. Add `work_lofi.wav` and `break_lofi.wav` to the app folder
            3. Restart and enjoy productive sessions!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}